# Generated by Django 3.1.6 on 2022-08-01 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nickname', models.CharField(max_length=128)),
                ('introduction', models.CharField(max_length=256, null=True)),
                ('image', models.ImageField(default='default.png', upload_to='profile/')),
                ('keyword1', models.CharField(max_length=24, null=True)),
                ('keyword2', models.CharField(max_length=24, null=True)),
                ('keyword3', models.CharField(max_length=24, null=True)),
            ],
        ),
    ]
