# Generated by Django 3.1.6 on 2022-08-03 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('persona', '0005_strength_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strength',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.profile'),
        ),
    ]
