# Generated by Django 3.1.6 on 2022-08-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weakness',
            name='hide',
        ),
    ]
