# Generated by Django 3.1.6 on 2022-08-06 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0015_remove_weakness_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HideLikes', models.BooleanField(default=False)),
                ('HideStrength', models.BooleanField(default=False)),
                ('HideWeakness', models.BooleanField(default=False)),
                ('HideValue', models.BooleanField(default=False)),
                ('HideSolve', models.BooleanField(default=False)),
                ('HideCareer', models.BooleanField(default=False)),
                ('HideLiteracy', models.BooleanField(default=False)),
                ('HideLanguage', models.BooleanField(default=False)),
                ('HideMBTI', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
