# Generated by Django 3.1.6 on 2022-08-07 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0018_auto_20220807_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hidepersona',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.profile'),
        ),
        migrations.AlterField(
            model_name='hidepersona',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
