# Generated by Django 3.1.6 on 2022-08-09 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20220807_2058'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0019_auto_20220807_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbti',
            name='profile',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='common.profile'),
        ),
        migrations.AlterField(
            model_name='mbti',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
